
package view;
import controller.EjemplaresDAO;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Ejemplares;


public class FormularioEjemplares extends javax.swing.JDialog {
    private String mode;
    private int id_ejemplar;
    private EjemplaresDAO dao;
    private ListadoEjemplares parent;

    /**
     * Creates new form FormularioLibros
     */
    public FormularioEjemplares(ListadoEjemplares parent, boolean modal, String mode, int id) {
        super(parent, modal);
        this.parent = parent;
        this.mode = mode;
        this.id_ejemplar = id;

        initComponents();
        setTitle("Formulario de Ejemplares");

        dao = new EjemplaresDAO();
        txt_id.setEnabled(false);

        if (mode.equals("INS")) {
            btn_guardar.setText("Insertar");
        } else if (mode.equals("UPD")) {
            Ejemplares d = (Ejemplares) dao.getById(id_ejemplar);
            if (d != null) {
               txt_id.setText(String.valueOf(d.getId_Ejemplar()));
                txt_idlibro.setText(String.valueOf(d.getId_Libro()));
                txt_piso.setText(String.valueOf(d.getPiso()));
                txt_pasillo.setText(String.valueOf(d.getPasillo()));
                txt_existencia.setText(String.valueOf(d.getExistencia()));
                
                btn_guardar.setText("Actualizar");
            }
        } else if (mode.equals("DLT")) {
            Ejemplares d = (Ejemplares) dao.getById(id_ejemplar);
            if (d != null) {
                txt_id.setText(String.valueOf(d.getId_Ejemplar()));
                txt_id.setEnabled(false);
                txt_idlibro.setText(String.valueOf(d.getId_Libro()));
                txt_idlibro.setEnabled(false);
                txt_piso.setText(String.valueOf(d.getPiso()));
                txt_piso.setEnabled(false);
                txt_pasillo.setText(String.valueOf(d.getPasillo()));
                txt_pasillo.setEnabled(false);
                txt_existencia.setText(String.valueOf(d.getExistencia()));
                txt_existencia.setEnabled(false);
                btn_guardar.setText("Eliminar");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_idlibro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Iddevolucion = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        txt_piso = new javax.swing.JTextField();
        idprestamo = new javax.swing.JLabel();
        IdLibro = new javax.swing.JLabel();
        txt_pasillo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        FechaDevolucion = new javax.swing.JLabel();
        txt_existencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_id.setEnabled(false);

        txt_idlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idlibroActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        Iddevolucion.setText("ID Libro");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        txt_piso.setColumns(4);
        txt_piso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pisoActionPerformed(evt);
            }
        });

        idprestamo.setText("Piso");

        IdLibro.setText("Pasillo");

        FechaDevolucion.setText("Existencia");

        txt_existencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_existenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_guardar)
                .addGap(18, 18, 18)
                .addComponent(btn_salir)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idprestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Iddevolucion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FechaDevolucion)
                            .addComponent(IdLibro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_existencia, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idlibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txt_piso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pasillo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iddevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idprestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLibro)
                    .addComponent(txt_pasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_existencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaDevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
            try {
        int idLibro = Integer.parseInt(txt_idlibro.getText());
        int piso = Integer.parseInt(txt_piso.getText());
        int pasillo = Integer.parseInt(txt_pasillo.getText());
        int existencia = Integer.parseInt(txt_existencia.getText());

        Ejemplares ejemplar = new Ejemplares();
        ejemplar.setId_Libro(idLibro);
        ejemplar.setPiso(piso);
        ejemplar.setPasillo(pasillo);
        ejemplar.setExistencia(existencia);

        boolean exito = false;

        switch (mode) {
            case "INS":
                exito = dao.insert(ejemplar);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Ejemplar insertado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al insertar el ejemplar.");
                }
                break;

            case "UPD":
                ejemplar.setId_Ejemplar(id_ejemplar); // se requiere para identificar cuál actualizar
                exito = dao.update(ejemplar);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Ejemplar actualizado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar el ejemplar.");
                }
                break;

            case "DLT":
                exito = dao.delete(id_ejemplar);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Ejemplar eliminado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar el ejemplar.");
                }
                break;
        }

        if (exito) {
            parent.refrescarInfo(); // actualiza la tabla en ListadoEjemplares
            this.dispose(); // cierra el formulario
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Todos los campos deben ser números válidos.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }
          

       

    
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_idlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idlibroActionPerformed

    private void txt_pisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pisoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_existenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_existenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_existenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEjemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaDevolucion;
    private javax.swing.JLabel IdLibro;
    private javax.swing.JLabel Iddevolucion;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel idprestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_existencia;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idlibro;
    private javax.swing.JTextField txt_pasillo;
    private javax.swing.JTextField txt_piso;
    // End of variables declaration//GEN-END:variables
}
