
package view;
import controller.DevolucionDAO;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Devolucion;


public class FormularioDevoluciones extends javax.swing.JDialog {
    private String mode;
    private int id_devolucion;
    private DevolucionDAO dao;
    private ListadoDevoluciones parent;

    /**
     * Creates new form FormularioLibros
     */
    public FormularioDevoluciones(ListadoDevoluciones parent, boolean modal, String mode, int id) {
        super(parent, modal);
        this.parent = parent;
        this.mode = mode;
        this.id_devolucion = id;

        initComponents();
        setTitle("Formulario de Devoluciones");

        dao = new DevolucionDAO();
        txt_id.setEnabled(false);

        if (mode.equals("INS")) {
            btn_guardar.setText("Insertar");
        } else if (mode.equals("UPD")) {
            Devolucion d = (Devolucion) dao.getById(id_devolucion);
            if (d != null) {
               txt_id.setText(String.valueOf(d.getId_devolucion()));
                txt_iddevolucion.setText(String.valueOf(d.getId_devolucion()));
                txt_idprestamo.setText(String.valueOf(d.getId_prestamo()));
                txt_idlibro.setText(String.valueOf(d.getId_libro()));
                txt_fechaDevolucion.setText(d.getFecha_devolucion().toString());
                btn_guardar.setText("Actualizar");
            }
        } else if (mode.equals("DLT")) {
            Devolucion d = (Devolucion) dao.getById(id_devolucion);
            if (d != null) {
                txt_id.setText(String.valueOf(d.getId_devolucion()));
                txt_id.setEnabled(false);
                txt_iddevolucion.setText(String.valueOf(d.getId_devolucion()));
                txt_iddevolucion.setEnabled(false);
                txt_idprestamo.setText(String.valueOf(d.getId_prestamo()));
                txt_idprestamo.setEnabled(false);
                txt_idlibro.setText(String.valueOf(d.getId_libro()));
                txt_idlibro.setEnabled(false);
                txt_fechaDevolucion.setText(d.getFecha_devolucion().toString());
                txt_fechaDevolucion.setEnabled(false);
                btn_guardar.setText("Eliminar");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_iddevolucion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Iddevolucion = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        txt_idprestamo = new javax.swing.JTextField();
        idprestamo = new javax.swing.JLabel();
        IdLibro = new javax.swing.JLabel();
        txt_idlibro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        FechaDevolucion = new javax.swing.JLabel();
        txt_fechaDevolucion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_id.setEnabled(false);

        txt_iddevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_iddevolucionActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        Iddevolucion.setText("ID Devolucion");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        txt_idprestamo.setColumns(4);
        txt_idprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idprestamoActionPerformed(evt);
            }
        });

        idprestamo.setText("ID Prestamo");

        IdLibro.setText("ID Libro");

        FechaDevolucion.setText("Fecha Devolucion:");

        txt_fechaDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_guardar)
                .addGap(18, 18, 18)
                .addComponent(btn_salir)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idprestamo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Iddevolucion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(IdLibro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FechaDevolucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_fechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_iddevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txt_idprestamo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_idlibro, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_iddevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iddevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idprestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLibro)
                    .addComponent(txt_idlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaDevolucion)
                    .addComponent(txt_fechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

           try {
        int idPrestamo = Integer.parseInt(txt_idprestamo.getText());
        int idLibro = Integer.parseInt(txt_idlibro.getText());
        Date fechaDevolucion;
        try {
       fechaDevolucion = Date.valueOf(txt_fechaDevolucion.getText());
       } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use AAAA-MM-DD.");
        return;
     }

        DevolucionDAO dao = new DevolucionDAO();

        if (dao.getByIdPrestamo(idPrestamo) != null) {
            JOptionPane.showMessageDialog(this, "Este préstamo ya fue devuelto.");
            return;
        }

        Devolucion devolucion = new Devolucion();
        devolucion.setId_prestamo(idPrestamo);
        devolucion.setId_libro(idLibro);
        devolucion.setFecha_devolucion(fechaDevolucion);

        boolean exito = dao.insert(devolucion);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Devolución registrada correctamente.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar devolución.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_iddevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_iddevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_iddevolucionActionPerformed

    private void txt_idprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idprestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idprestamoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_fechaDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaDevolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDevoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaDevolucion;
    private javax.swing.JLabel IdLibro;
    private javax.swing.JLabel Iddevolucion;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel idprestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_fechaDevolucion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_iddevolucion;
    private javax.swing.JTextField txt_idlibro;
    private javax.swing.JTextField txt_idprestamo;
    // End of variables declaration//GEN-END:variables
}
