
package view;
import controller.PrestamoDAO;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Prestamos;

public class FormularioPrestamos extends javax.swing.JDialog {
     private String mode;
    private int id_prestamo;
    private PrestamoDAO dao;
    private ListadoPrestamos parent;

  
    public FormularioPrestamos(ListadoPrestamos pParent, boolean modal, String pMode, int pId_prestamo) {
        super(pParent, modal);
        initComponents();
        this.parent = pParent;
        this.dao = new PrestamoDAO();
        this.mode = pMode;
        this.id_prestamo = pId_prestamo;
        setTitle("Formulario de Préstamos");

        txt_id.setText(String.valueOf(pId_prestamo));
        txt_id.setEnabled(false);

        if (mode.equals("INS")) {
            btn_accion.setText("Insertar");
        } else {
            cargarDatos();
            if (mode.equals("UPD")) {
                btn_accion.setText("Actualizar");
            } else if (mode.equals("DLT")) {
                btn_accion.setText("Eliminar");
                deshabilitarCampos();
            }
        }
    }

    private void cargarDatos() {
        Prestamos p = dao.getById(id_prestamo);
        if (p != null) {
            txt_idLibro.setText(String.valueOf(p.getId_Libro()));
            txt_cantidad.setText(String.valueOf(p.getCantidad()));
            txt_idUsuario.setText(String.valueOf(p.getId_Usuario()));
            txt_idEmpleado.setText(String.valueOf(p.getId_Empleado()));
            txt_fechaPrestamo.setText(p.getFecha_Prestamo().toString());
            txt_fechaLimite.setText(p.getFecha_limite().toString());
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cargar el préstamo.");
        }
    }

    private void deshabilitarCampos() {
        txt_idLibro.setEnabled(false);
        txt_cantidad.setEnabled(false);
        txt_idUsuario.setEnabled(false);
        txt_idEmpleado.setEnabled(false);
        txt_fechaPrestamo.setEnabled(false);
        txt_fechaLimite.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_id = new javax.swing.JTextField();
        txt_idLibro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IdLibro = new javax.swing.JLabel();
        btn_accion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JLabel();
        txt_idUsuario = new javax.swing.JTextField();
        Idempleado = new javax.swing.JLabel();
        Fechalimite = new javax.swing.JLabel();
        txt_idEmpleado = new javax.swing.JTextField();
        txt_fechaLimite = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        FechaPrestamo = new javax.swing.JLabel();
        txt_fechaPrestamo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_id.setEnabled(false);

        txt_idLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idLibroActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        IdLibro.setText("ID Libro");

        btn_accion.setText("jButton1");
        btn_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accionActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        txt_cantidad.setColumns(4);
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        Cantidad.setText("Cantidad");

        IdUsuario.setText("ID Usuario");

        Idempleado.setText("ID Empleado");

        Fechalimite.setText("Fecha Limite:");

        txt_idEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idEmpleadoActionPerformed(evt);
            }
        });

        txt_fechaLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaLimiteActionPerformed(evt);
            }
        });

        FechaPrestamo.setText("Fecha Prestamo:");

        txt_fechaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(354, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fechalimite)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(IdLibro)
                                                    .addComponent(jLabel1))
                                                .addComponent(Cantidad))
                                            .addGap(9, 9, 9))
                                        .addComponent(Idempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FechaPrestamo)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idLibro)
                            .addComponent(txt_idEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txt_cantidad)
                            .addComponent(txt_idUsuario)
                            .addComponent(txt_fechaLimite)
                            .addComponent(txt_fechaPrestamo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_accion)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdLibro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdUsuario)
                            .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Idempleado)
                        .addGap(6, 6, 6))
                    .addComponent(txt_idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fechalimite)
                    .addComponent(txt_fechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaPrestamo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accionActionPerformed
         try {
            Prestamos prestamo = new Prestamos();
            if (!mode.equals("INS")) prestamo.setId_Prestamo(id_prestamo);
            prestamo.setId_Libro(Integer.parseInt(txt_idLibro.getText()));
            prestamo.setCantidad(Integer.parseInt(txt_cantidad.getText()));
            prestamo.setId_Usuario(Integer.parseInt(txt_idUsuario.getText()));
            prestamo.setId_Empleado(Integer.parseInt(txt_idEmpleado.getText()));
            Date fechaPrestamo;
         try {
           fechaPrestamo = Date.valueOf(txt_fechaPrestamo.getText());
         } catch (IllegalArgumentException e) {
           JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use AAAA-MM-DD en Fecha Préstamo.");
           return;
}

           Date fechaLimite;
         try {
          fechaLimite = Date.valueOf(txt_fechaLimite.getText());
         } catch (IllegalArgumentException e) {
          JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use AAAA-MM-DD en Fecha Límite.");
          return;
}

prestamo.setFecha_Prestamo(fechaPrestamo);
prestamo.setFecha_limite(fechaLimite);

            switch (mode) {
                case "INS" -> dao.insert(prestamo);
                case "UPD" -> dao.update(prestamo);
                case "DLT" -> dao.delete(id_prestamo);
            }

            parent.refrescarInfo();
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btn_accionActionPerformed

    private void txt_fechaLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaLimiteActionPerformed

    private void txt_idLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idLibroActionPerformed

    private void txt_idEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idEmpleadoActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_fechaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

         //</editor-fold>
         //</editor-fold>
         /* Create and display the dialog */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel FechaPrestamo;
    private javax.swing.JLabel Fechalimite;
    private javax.swing.JLabel IdLibro;
    private javax.swing.JLabel IdUsuario;
    private javax.swing.JLabel Idempleado;
    private javax.swing.JButton btn_accion;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_fechaLimite;
    private javax.swing.JTextField txt_fechaPrestamo;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idEmpleado;
    private javax.swing.JTextField txt_idLibro;
    private javax.swing.JTextField txt_idUsuario;
    // End of variables declaration//GEN-END:variables

  
    
}
