/*Revision 24/07/2025*/
package view;

import controller.UsuariosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Usuarios;

/**
 *
 * @author Novitus
 */
public class ListadoUsuarios extends javax.swing.JFrame {
       private DefaultTableModel modeloTabla;
       private UsuariosDAO  usuarioDAO = new UsuariosDAO();

    /**
     * Creates new form ListadoLibros
     */
    public ListadoUsuarios() {
        initComponents();
        setTitle("Consulta de Usuarios");
        modeloTabla = (DefaultTableModel) tbl_usuarios.getModel();
        setLocationRelativeTo(null);
        configurarColumnas();
        cargarDatos();
    }
    
    private void cargarDatos(){
        modeloTabla.setRowCount(0); 
        List<Object> usuario = usuarioDAO.getAll();
        for(Object usuario_uncast : usuario){
            Usuarios usuarios = (Usuarios) usuario_uncast;           
           modeloTabla.addRow(new Object[]{usuarios.getId_Usuario(),
               usuarios.getdni_Usuario(),
               usuarios.getnombre_Usuario(),usuarios.gettipo_Usuario() + " - " + usuarios.getntipo_Usuario(),
               usuarios.getcorreo(),usuarios.gettelefono()});
        }
    }
    
    public void refrescarInfo(){
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        btn_inertar = new javax.swing.JButton();
        txt_salir = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "DNI", "Nombre", "Tipo Usuario", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_usuarios);
        if (tbl_usuarios.getColumnModel().getColumnCount() > 0) {
            tbl_usuarios.getColumnModel().getColumn(0).setResizable(false);
            tbl_usuarios.getColumnModel().getColumn(1).setResizable(false);
            tbl_usuarios.getColumnModel().getColumn(2).setResizable(false);
            tbl_usuarios.getColumnModel().getColumn(3).setResizable(false);
            tbl_usuarios.getColumnModel().getColumn(4).setResizable(false);
            tbl_usuarios.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_inertar.setText("Insertar");
        btn_inertar.setPreferredSize(new java.awt.Dimension(83, 23));
        btn_inertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inertarActionPerformed(evt);
            }
        });

        txt_salir.setText("Salir");
        txt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salirActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(btn_inertar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inertar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inertarActionPerformed
        // TODO add your handling code here:
         FormularioUsuarios formulario = new FormularioUsuarios(this, true, "INS",0);
         formulario.setVisible(true);
    }//GEN-LAST:event_btn_inertarActionPerformed

    private void txt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txt_salirActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tbl_usuarios.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        int id = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioUsuarios formulario = new FormularioUsuarios(this, true, "UPD",id);
         formulario.setVisible(true);
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
      int filaSeleccionada = tbl_usuarios.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        int id = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioUsuarios formulario = new FormularioUsuarios(this, true, "DLT",id);
         formulario.setVisible(true);  
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoUsuarios().setVisible(true);
            }
        });
    }
    
    
    private void configurarColumnas() {
    tbl_usuarios.getColumnModel().getColumn(0).setPreferredWidth(30);   
    tbl_usuarios.getColumnModel().getColumn(1).setPreferredWidth(140);  
    tbl_usuarios.getColumnModel().getColumn(2).setPreferredWidth(150);  
    tbl_usuarios.getColumnModel().getColumn(3).setPreferredWidth(180);  
    tbl_usuarios.getColumnModel().getColumn(4).setPreferredWidth(100);  

    // Evita que el usuario cambie el tamaño
    for (int i = 0; i < tbl_usuarios.getColumnCount(); i++) {
        tbl_usuarios.getColumnModel().getColumn(i).setResizable(false);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_inertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usuarios;
    private javax.swing.JButton txt_salir;
    // End of variables declaration//GEN-END:variables
}
