/*Revision 24/07/2025*/
package view;

import controller.EjemplaresDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ejemplares;



public class ListadoEjemplares extends javax.swing.JFrame {
           DefaultTableModel modeloTabla;   
           EjemplaresDAO dao = new EjemplaresDAO();

   
    public ListadoEjemplares() {
        initComponents();
        setTitle("Consulta de Ejemplares");
        modeloTabla = (DefaultTableModel) tbl_ejemplares.getModel();
        setLocationRelativeTo(null);
        configurarColumnas();
        cargarDatos();
    }
    
    private void cargarDatos() {
    modeloTabla.setRowCount(0);
        List<Object> ejemplares = dao.getAll();
        for (Object ejemplarObj : ejemplares) {
            Ejemplares d = (Ejemplares) ejemplarObj;
            modeloTabla.addRow(new Object[]{
               d.getId_Ejemplar(),
               d.getId_Libro(),
               d.getPiso(),
               d.getPasillo(),
               d.getExistencia()
            });
        }
}
    
    public void refrescarInfo(){
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ejemplares = new javax.swing.JTable();
        btn_insertar = new javax.swing.JButton();
        txt_salir = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_ejemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Libro", "Piso", "Pasillo", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_ejemplares);
        if (tbl_ejemplares.getColumnModel().getColumnCount() > 0) {
            tbl_ejemplares.getColumnModel().getColumn(0).setResizable(false);
            tbl_ejemplares.getColumnModel().getColumn(1).setResizable(false);
            tbl_ejemplares.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_insertar.setText("Insertar");
        btn_insertar.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        txt_salir.setText("Salir");
        txt_salir.setPreferredSize(new java.awt.Dimension(90, 23));
        txt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salirActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btn_delete.setText("Borrar");
        btn_delete.setPreferredSize(new java.awt.Dimension(90, 23));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
       FormularioEjemplares form = new FormularioEjemplares(this, true, "INS", 0);
        form.setVisible(true);
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void txt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salirActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_txt_salirActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed

         int fila = tbl_ejemplares.getSelectedRow();
        if (fila >= 0) {
            int id_ejemplar = Integer.parseInt(tbl_ejemplares.getValueAt(fila, 0).toString());
            FormularioEjemplares form = new FormularioEjemplares(this, true, "UPD", id_ejemplar);
            form.setVisible(true);
            cargarDatos();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro primero.");
        }
     
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

     int fila = tbl_ejemplares.getSelectedRow();
        if (fila >= 0) {
            int id_ejemplar = Integer.parseInt(tbl_ejemplares.getValueAt(fila, 0).toString());
            int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar estos datos?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                dao.delete(id_ejemplar);
                cargarDatos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro primero.");
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ListadoEjemplares().setVisible(true);
        });
    }
    
    
     private void configurarColumnas() {
    tbl_ejemplares.getColumnModel().getColumn(0).setPreferredWidth(10);   
    tbl_ejemplares.getColumnModel().getColumn(1).setPreferredWidth(140);  
    tbl_ejemplares.getColumnModel().getColumn(2).setPreferredWidth(25);  
    tbl_ejemplares.getColumnModel().getColumn(3).setPreferredWidth(70);  

    
    //tbl_libros.getColumnModel().getColumn(6).setPreferredWidth(100);  

    // Evita que el usuario cambie el tamaño
    for (int i = 0; i < tbl_ejemplares.getColumnCount(); i++) {
        tbl_ejemplares.getColumnModel().getColumn(i).setResizable(false);
    }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ejemplares;
    private javax.swing.JButton txt_salir;
    // End of variables declaration//GEN-END:variables
}
