/*Revision 24/07/2025*/
package view;

/**
 *
 * @author Novitus
 */

import java.awt.Image;
import view.ListadoLibros;
import view.ListadoPrestamos;
import view.ListadoUsuarios;
import view.ListadoDevoluciones;
import javax.swing.*;



public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String nombre_usuario, int tipo_usuario) {
        initComponents();       
        setLocationRelativeTo(null);
                
        this.setSize(800, 600);
        
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        int anchoVentana = this.getWidth();
        int anchoLabel = jLabel1.getWidth();
        int posX = (anchoVentana - anchoLabel) / 2;
        jLabel1.setLocation(posX, 20); // 20 es la posición Y (desde arriba)        
        
               
        this.getContentPane().setLayout(null);
        lblFondo = new javax.swing.JLabel();
        
        
         if (tipo_usuario == 1001) { // Alumno
        btnLibros.setEnabled(false);
        btnUsuarios.setEnabled(false);
        btnDevolucion.setEnabled(false);
        btnAutores.setEnabled(false);
        btnCategoria.setEnabled(false);
        btnEmpleados.setEnabled(false);
        btnTransacciones.setEnabled(false);
    }
    
       
       ImageIcon fondoOriginal = new ImageIcon(getClass().getResource("/view/bg.jpg"));
        Image imagenEscalada = fondoOriginal.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        lblFondo.setIcon(new ImageIcon(imagenEscalada));
        lblFondo.setBounds(0, 0, this.getWidth(), this.getHeight());

        // Agregarlo al final para que quede detrás de todo
        this.getContentPane().add(lblFondo);
        
        
        
        
        
        
        btnLibros.addActionListener(evt ->{
            new ListadoLibros().setVisible(true);            
        });
        
        btnUsuarios.addActionListener(evt ->{
            new ListadoUsuarios().setVisible(true);            
        });
        
        btnUsuarios.addActionListener(evt ->{
            new ListadoUsuarios().setVisible(true);            
        });
        
        btnPrestamos.addActionListener(evt ->{
            new ListadoPrestamos().setVisible(true);            
        });
        
        btnDevolucion.addActionListener(evt ->{
            new ListadoDevoluciones().setVisible(true);            
        });
        
        btnEjemplares.addActionListener(evt ->{
            new ListadoEjemplares().setVisible(true);            
        });
        
        btnAutores.addActionListener(evt ->{
            new ListadoAutores().setVisible(true);            
        });
        
        btnCategoria.addActionListener(evt ->{
            new ListadoCategorias().setVisible(true);            
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLibros = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        btnAutores = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnEjemplares = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnTransacciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Biblioteca - Menu Principal");

        btnLibros.setText("Libros");

        btnPrestamos.setText("Prestamos");

        btnUsuarios.setText("Usuarios");

        btnDevolucion.setText("Devoluciones");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIBLIOTECA HONDURAS");

        btnAutores.setText("Autores");

        btnCategoria.setText("Categorias");

        btnEjemplares.setText("Ejemplares");

        btnEmpleados.setText("Empleados");

        btnTransacciones.setText("Transacciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransacciones)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFondo)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolucion)
                    .addComponent(btnUsuarios)
                    .addComponent(btnPrestamos)
                    .addComponent(btnLibros)
                    .addComponent(btnTransacciones))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpleados)
                    .addComponent(btnEjemplares)
                    .addComponent(btnCategoria)
                    .addComponent(btnAutores))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnEjemplares;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}

